### ISSUE TITLE
Git clone not grabbing latest 

### ISSUE THREAD

**Issue by ethanopp** [arontx/docker-sonarr-mp4-automator#2]
Thanks for creating this!

postSonarr.py and postRadarr.py recently got updated on master but when re-flashing this image it seems these new files are not getting cloned?

https://github.com/mdhiggins/sickbeard_mp4_automator/pull/852

**Comment by arontx** [comment]
Not sure if this was related to #3 or not but the latest build reflects the changes to postSonarr.py/postRadarr.py
