### ISSUE TITLE
Broken by PIP Version 10

### ISSUE THREAD

**Issue by zachawii** [arontx/docker-sonarr-mp4-automator#3]
Hello, your automated builds were broken by PIP Version 10, which changed some of the library locations. I have solved this in my fork by holding PIP back to Version 9.0.3, but i'm sure there is a less-unfutureproof solution.

**Comment by arontx** [comment]
If you make a pull request with your changes I'll review

(Sorry I'm just now getting to this.. my server has been out of commission so I had not been paying attention.)

**Comment by zachawii** [comment]
Alright, I have created the necessary pull requests, add them and try to manually build a container.

**Comment by arontx** [comment]
Pull request tested and merged. Automated build reports success. Thanks for your contribution!
