### ISSUE TITLE
Problem with last docker commit

### ISSUE THREAD

**Issue by notorius28** [arontx/docker-sonarr-mp4-automator#5]
Hello:

Concerning this error
[link](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/948)
it seems that last versions of your docker packages aren't working well, related to the deep copy issue.

The dev has already fixed that, so could you compile a new version of your docker packages?

Thank you!

**Comment by zachawii** [comment]
@arontx This should be solved now
